[package]
name = "large_deviation_merger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"]}
serde_json = "*"
sampling = { git = "https://github.com/Pardoxa/sampling.git", rev = "c976c0cf954491c327c7eb89bf7dca8badb360ab" }
structopt = "^0.3.26"